name: build picowake java
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - java/**
jobs:
  push:
    name: "yolks:eco_minecraft_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 21

    permissions:
        contents: read
        packages: write
        attestations: write

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./eco_minecraft
          file: ./eco_minecraft/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/quozul/yolks:eco_minecraft_${{ matrix.tag }}
